//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationsMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessedForm
    {
        public int Application_id { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> date_of_resolve { get; set; }
        public string resolved_By { get; set; }
        public string status { get; set; }
    
        public virtual ApplicationForm ApplicationForm { get; set; }
    }
}
